framework:
    messenger:
        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            producer:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    flushTimeout: 10000
                    flushRetries: 5
                    topic:
                        name: 'messages'
                    kafka_conf:
                        log_level: '7'
                        metadata.broker.list: '%env(KAFKA_BROKERS)%'
                        message.send.max.retries: '5'
            consumer:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    commitAsync: true
                    receiveTimeout: 10000
                    topic:
                        name: 'messages'
                    kafka_conf:
                        enable.auto.offset.store: 'false'
                        group.id: 'my-group-id'
                        log_level: '7'
                        enable.auto.commit: 'true'
                        metadata.broker.list: '%env(KAFKA_BROKERS)%'
                        security.protocol: 'plaintext' # plaintext, ssl, sasl_plaintext, sasl_ssl
                        auto.offset.reset: 'earliest' # 'earliest': start from the beginning
                        enable.partition.eof: 'true' # Emit EOF event when reaching the end of a partition
                        max.poll.interval.ms: '45000'
                    topic_conf:
                        auto.offset.reset: 'earliest'

            #failed: 'doctrine://default?queue_name=failed'
            # sync: 'sync://'

        default_bus: messenger.bus.default

        buses:
            messenger.bus.default: []

        routing:
            #Symfony\Component\Mailer\Messenger\SendEmailMessage: async

            # Route your messages to the transports
            # 'App\Message\YourMessage': async
