version: '3.8'

services:
  php-fpm:
    build:
      context: ./docker/php-fpm
      dockerfile: Dockerfile
      args:
        XDEBUG_CLIENT_HOST: 172.59.0.1
        XDEBUG_CLIENT_PORT: 9000
    image: php-fpm
    restart: always
    volumes:
      - ./:/app
      - ./docker/tmp:/tmp/tmp:rw
    working_dir: /app
    hostname: 'localhost'
    networks:
      - app-network
    environment:
      XDEBUG_CONFIG: client_host=172.59.0.1 client_port=9000 remote_enable=1
      PHP_IDE_CONFIG: serverName=localhost
      DEV: 1

  nginx:
    image: nginx:1.25-alpine
    depends_on:
      - php-fpm
    working_dir: /app
    ports:
      - '28080:80'
      - '28081:81'
    networks:
      - app-network
    restart: always
    volumes:
      - ./:/app
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf

  db:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    volumes:
      - database_data:/var/lib/postgresql/data:rw
    networks:
      - app-network
    ports:
      - "5432:5432"  # если нужен доступ с хоста

  kafka:
    image: docker.io/bitnami/kafka:3.6
    ports:
      - "28092:9092"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:28092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
    networks:
      - app-network
      - kafka-network

volumes:
  database_data:
  kafka_data:

networks:
  app-network:
    driver: bridge
  kafka-network:
    driver: bridge